export default {
  data () {
    return {
      tokenDetails: [
        {
          name: 'SimpleERC20',
          version: '4.0.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: false,
          supplyType: 'Fixed',
          accessType: 'None',
          mintable: false,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: false,
          price: 0,
          gas: 1163434,
        },
        {
          name: 'StandardERC20',
          version: '4.0.1',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Fixed',
          accessType: 'None',
          mintable: false,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          price: 0.15,
          gas: 1113949,
        },
        {
          name: 'BurnableERC20',
          version: '4.2.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Fixed',
          accessType: 'None',
          mintable: false,
          burnable: true,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          price: 0.25,
          gas: 1320960,
        },
        {
          name: 'MintableERC20',
          version: '4.1.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Unlimited',
          accessType: 'Ownable',
          mintable: true,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          price: 0.35,
          gas: 1623484,
        },
        {
          name: 'CommonERC20',
          version: '4.0.1',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Capped',
          accessType: 'Ownable',
          mintable: true,
          burnable: true,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          price: 0.55,
          gas: 1909651,
        },
        {
          name: 'UnlimitedERC20',
          version: '4.4.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Unlimited',
          accessType: 'Role Based',
          mintable: true,
          burnable: true,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          price: 0.65,
          gas: 2606071,
        },
        {
          name: 'AmazingERC20',
          version: '4.4.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Unlimited',
          accessType: 'Ownable',
          mintable: true,
          burnable: true,
          erc1363: true,
          tokenRecover: true,
          removeCopyright: true,
          price: 0.85,
          gas: 2655189,
        },
        {
          name: 'PowerfulERC20',
          version: '4.3.0',
          standard: true,
          verified: true,
          detailed: true,
          customizeDecimals: true,
          supplyType: 'Capped',
          accessType: 'Role Based',
          mintable: true,
          burnable: true,
          erc1363: true,
          tokenRecover: true,
          removeCopyright: true,
          price: 0.95,
          gas: 3516237,
        },
      ],
    };
  },
};
