export default {
  data () {
    return {
      tokenDetails: [
        {
          name: 'SimpleERC20',
          version: '4.0.0',
          customizeDecimals: false,
          standard: true,
          detailed: true,
          supplyType: 'Fixed',
          mintable: false,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: false,
          price: 0,
        },
        {
          name: 'StandardERC20',
          version: '4.0.1',
          customizeDecimals: true,
          standard: true,
          detailed: true,
          supplyType: 'Fixed',
          mintable: false,
          burnable: false,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          price: 0.15,
        },
        {
          name: 'CommonERC20',
          version: '4.0.1',
          customizeDecimals: true,
          standard: true,
          detailed: true,
          supplyType: 'Capped',
          mintable: true,
          burnable: true,
          erc1363: false,
          tokenRecover: false,
          removeCopyright: true,
          price: 0.55,
        },
        {
          name: 'PowerfulERC20',
          version: '4.0.1',
          customizeDecimals: true,
          standard: true,
          detailed: true,
          supplyType: 'Capped',
          mintable: true,
          burnable: true,
          erc1363: true,
          tokenRecover: true,
          removeCopyright: true,
          price: 0.95,
        },
      ],
    };
  },
};
